/** Generated by YAKINDU Statechart Tools code generator. */

#include "System.h"
#include "..\src\sc_types.h"
#include "SystemRequired.h"

/*! \file Implementation of the state machine 'system'
*/

#define SC_UNUSED(P) (void)(P)
/* prototypes of all internal functions */
static void enact_rDefault_Default_Work_Routine_r1_Measure(System* handle);
static void enact_rDefault_Init(System* handle);
static void enact_rDefault_Menu(System* handle);
static void exact_rDefault_Default_Work_Routine_r1_Measure(System* handle);
static void enseq_rDefault_Default_Work_Routine_default(System* handle);
static void enseq_rDefault_Default_Work_Routine_r1_Measure_default(System* handle);
static void enseq_rDefault_Default_Work_Routine_r1_Sprinkle_default(System* handle);
static void enseq_rDefault_Init_default(System* handle);
static void enseq_rDefault_Menu_default(System* handle);
static void enseq_rDefault_Soil_Moisture_default(System* handle);
static void enseq_rDefault_Temperature_default(System* handle);
static void enseq_rDefault_Humidity_default(System* handle);
static void enseq_rDefault_Air_Pressure_default(System* handle);
static void enseq_rDefault_Rain_default(System* handle);
static void enseq_rDefault_USB_default(System* handle);
static void enseq_rDefault_default(System* handle);
static void enseq_rDefault_Default_Work_Routine_r1_default(System* handle);
static void exseq_rDefault_Default_Work_Routine(System* handle);
static void exseq_rDefault_Default_Work_Routine_r1_Measure(System* handle);
static void exseq_rDefault_Default_Work_Routine_r1_Sprinkle(System* handle);
static void exseq_rDefault_Init(System* handle);
static void exseq_rDefault_Menu(System* handle);
static void exseq_rDefault_Soil_Moisture(System* handle);
static void exseq_rDefault_Temperature(System* handle);
static void exseq_rDefault_Humidity(System* handle);
static void exseq_rDefault_Air_Pressure(System* handle);
static void exseq_rDefault_Rain(System* handle);
static void exseq_rDefault_USB(System* handle);
static void exseq_rDefault(System* handle);
static void exseq_rDefault_Default_Work_Routine_r1(System* handle);
static void react_rDefault__entry_Default(System* handle);
static void react_rDefault_Default_Work_Routine_r1__entry_Default(System* handle);
static sc_boolean react(System* handle);
static sc_boolean rDefault_Default_Work_Routine_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Default_Work_Routine_r1_Measure_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Default_Work_Routine_r1_Sprinkle_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Init_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Menu_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Soil_Moisture_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Temperature_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Humidity_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Air_Pressure_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_Rain_react(System* handle, const sc_boolean try_transition);
static sc_boolean rDefault_USB_react(System* handle, const sc_boolean try_transition);
static void clearInEvents(System* handle);
static void clearOutEvents(System* handle);

static void system_eventqueue_init(system_eventqueue * eq);
static sc_integer system_eventqueue_size(system_eventqueue * eq);
static system_internal_event system_eventqueue_pop(system_eventqueue * eq);
static sc_boolean system_eventqueue_push(system_eventqueue * eq, system_internal_event ev);
static void system_internal_event_init(system_internal_event * ev, system_event_name name);
static void system_add_event_to_queue(system_eventqueue * eq, system_event_name name);
static void system_dispatch_event(System* handle, const system_internal_event * event);
static system_internal_event system_get_next_event(System* handle);


void system_init(System* handle)
{
	sc_integer i;
	
	for (i = 0; i < SYSTEM_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = System_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
	/* Default init sequence for statechart system */
	handle->ifaceScreen.text = "";
	handle->internal.targetSoilMoisture = 0;
	handle->internal.targetTemperature = 0;
	handle->internal.targetHumidity = 0;
	handle->internal.targetAirPressure = 0;
	handle->internal.bRain = bool_false;
	handle->internal.soilMoisture = 0;
	handle->internal.temperature = 0;
	handle->internal.humidity = 0;
	handle->internal.airPressure = 0;
	handle->internal.rain = bool_false;
	handle->internal.sprinkleOn = bool_false;
	system_eventqueue_init(&(handle->internal_event_queue));
}

void system_enter(System* handle)
{
	/* Default enter sequence for statechart system */
	enseq_rDefault_default(handle);
}

void system_runCycle(System* handle)
{
	clearOutEvents(handle);
	
	system_internal_event currentEvent = system_get_next_event(handle);
	
	do {
		system_dispatch_event(handle, &currentEvent);
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < SYSTEM_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case System_rDefault_Default_Work_Routine_r1_Measure:
			{
				rDefault_Default_Work_Routine_r1_Measure_react(handle, bool_true);
				break;
			}
			case System_rDefault_Default_Work_Routine_r1_Sprinkle:
			{
				rDefault_Default_Work_Routine_r1_Sprinkle_react(handle, bool_true);
				break;
			}
			case System_rDefault_Init:
			{
				rDefault_Init_react(handle, bool_true);
				break;
			}
			case System_rDefault_Menu:
			{
				rDefault_Menu_react(handle, bool_true);
				break;
			}
			case System_rDefault_Soil_Moisture:
			{
				rDefault_Soil_Moisture_react(handle, bool_true);
				break;
			}
			case System_rDefault_Temperature:
			{
				rDefault_Temperature_react(handle, bool_true);
				break;
			}
			case System_rDefault_Humidity:
			{
				rDefault_Humidity_react(handle, bool_true);
				break;
			}
			case System_rDefault_Air_Pressure:
			{
				rDefault_Air_Pressure_react(handle, bool_true);
				break;
			}
			case System_rDefault_Rain:
			{
				rDefault_Rain_react(handle, bool_true);
				break;
			}
			case System_rDefault_USB:
			{
				rDefault_USB_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		
		clearInEvents(handle);
	} while((currentEvent = system_get_next_event(handle)).name != system_invalid_event);
	
}

void system_exit(System* handle)
{
	/* Default exit sequence for statechart system */
	exseq_rDefault(handle);
}

sc_boolean system_isActive(const System* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < SYSTEM_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != System_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean system_isFinal(const System* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void system_raiseTimeEvent(System* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(SystemTimeEvents))
	{
		*(sc_boolean*)evid = bool_true;
		
		system_runCycle(handle);
	}
}

sc_boolean system_isStateActive(const System* handle, SystemStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case System_rDefault_Default_Work_Routine :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_DEFAULT_WORK_ROUTINE] >= System_rDefault_Default_Work_Routine
				&& handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_DEFAULT_WORK_ROUTINE] <= System_rDefault_Default_Work_Routine_r1_Sprinkle);
			break;
		case System_rDefault_Default_Work_Routine_r1_Measure :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_DEFAULT_WORK_ROUTINE_R1_MEASURE] == System_rDefault_Default_Work_Routine_r1_Measure
			);
			break;
		case System_rDefault_Default_Work_Routine_r1_Sprinkle :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_DEFAULT_WORK_ROUTINE_R1_SPRINKLE] == System_rDefault_Default_Work_Routine_r1_Sprinkle
			);
			break;
		case System_rDefault_Init :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_INIT] == System_rDefault_Init
			);
			break;
		case System_rDefault_Menu :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_MENU] == System_rDefault_Menu
			);
			break;
		case System_rDefault_Soil_Moisture :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_SOIL_MOISTURE] == System_rDefault_Soil_Moisture
			);
			break;
		case System_rDefault_Temperature :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_TEMPERATURE] == System_rDefault_Temperature
			);
			break;
		case System_rDefault_Humidity :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_HUMIDITY] == System_rDefault_Humidity
			);
			break;
		case System_rDefault_Air_Pressure :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_AIR_PRESSURE] == System_rDefault_Air_Pressure
			);
			break;
		case System_rDefault_Rain :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_RAIN] == System_rDefault_Rain
			);
			break;
		case System_rDefault_USB :
			result = (sc_boolean) (handle->stateConfVector[SCVI_SYSTEM_RDEFAULT_USB] == System_rDefault_USB
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(System* handle)
{
	handle->ifaceButtons.matrix0_raised = bool_false;
	handle->ifaceButtons.matrix1_raised = bool_false;
	handle->ifaceButtons.matrix2_raised = bool_false;
	handle->ifaceButtons.matrix3_raised = bool_false;
	handle->ifaceButtons.matrix4_raised = bool_false;
	handle->ifaceButtons.matrix5_raised = bool_false;
	handle->ifaceButtons.matrix6_raised = bool_false;
	handle->ifaceButtons.matrix7_raised = bool_false;
	handle->ifaceButtons.matrix8_raised = bool_false;
	handle->ifaceButtons.matrix9_raised = bool_false;
	handle->ifaceButtons.matrixStar_raised = bool_false;
	handle->ifaceButtons.matrixHash_raised = bool_false;
	handle->internal.InitFinished_raised = bool_false;
	handle->internal.Raining_raised = bool_false;
	handle->internal.ConditionsMet_raised = bool_false;
	handle->timeEvents.system_rDefault_Default_Work_Routine_r1_Measure_tev0_raised = bool_false;
}

static void clearOutEvents(System* handle)
{
	SC_UNUSED(handle);
}





sc_string systemIfaceScreen_get_text(const System* handle)
{
	return handle->ifaceScreen.text;
}
void systemIfaceScreen_set_text(System* handle, sc_string value)
{
	handle->ifaceScreen.text = value;
}
void systemIfaceButtons_raise_matrix0(System* handle)
{
	handle->ifaceButtons.matrix0_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix1(System* handle)
{
	handle->ifaceButtons.matrix1_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix2(System* handle)
{
	handle->ifaceButtons.matrix2_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix3(System* handle)
{
	handle->ifaceButtons.matrix3_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix4(System* handle)
{
	handle->ifaceButtons.matrix4_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix5(System* handle)
{
	handle->ifaceButtons.matrix5_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix6(System* handle)
{
	handle->ifaceButtons.matrix6_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix7(System* handle)
{
	handle->ifaceButtons.matrix7_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix8(System* handle)
{
	handle->ifaceButtons.matrix8_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrix9(System* handle)
{
	handle->ifaceButtons.matrix9_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrixStar(System* handle)
{
	handle->ifaceButtons.matrixStar_raised = bool_true;
	
	system_runCycle(handle);
}
void systemIfaceButtons_raise_matrixHash(System* handle)
{
	handle->ifaceButtons.matrixHash_raised = bool_true;
	
	system_runCycle(handle);
}



/* implementations of all internal functions */

/* Entry action for state 'Measure'. */
static void enact_rDefault_Default_Work_Routine_r1_Measure(System* handle)
{
	/* Entry action for state 'Measure'. */
	system_setTimer(handle, (sc_eventid) &(handle->timeEvents.system_rDefault_Default_Work_Routine_r1_Measure_tev0_raised) , (300 * 1000), bool_true);
	systemInternal_measure(handle);
	systemInternal_sleep(handle);
}

/* Entry action for state 'Init'. */
static void enact_rDefault_Init(System* handle)
{
	/* Entry action for state 'Init'. */
	system_add_event_to_queue(&(handle->internal_event_queue), systemInternal_InitFinished)
	;
}

/* Entry action for state 'Menu'. */
static void enact_rDefault_Menu(System* handle)
{
	/* Entry action for state 'Menu'. */
	handle->ifaceScreen.text = "
	1: Soil moisture
	2: Temperature
	3: Humidity
	4: Air Pressure
	5: Rain
	6: USB
	";
}

/* Exit action for state 'Measure'. */
static void exact_rDefault_Default_Work_Routine_r1_Measure(System* handle)
{
	/* Exit action for state 'Measure'. */
	system_unsetTimer(handle, (sc_eventid) &(handle->timeEvents.system_rDefault_Default_Work_Routine_r1_Measure_tev0_raised) );		
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state Default Work Routine */
static void enseq_rDefault_Default_Work_Routine_default(System* handle)
{
	/* 'default' enter sequence for state Default Work Routine */
	enseq_rDefault_Default_Work_Routine_r1_default(handle);
}

/* 'default' enter sequence for state Measure */
static void enseq_rDefault_Default_Work_Routine_r1_Measure_default(System* handle)
{
	/* 'default' enter sequence for state Measure */
	enact_rDefault_Default_Work_Routine_r1_Measure(handle);
	handle->stateConfVector[0] = System_rDefault_Default_Work_Routine_r1_Measure;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Sprinkle */
static void enseq_rDefault_Default_Work_Routine_r1_Sprinkle_default(System* handle)
{
	/* 'default' enter sequence for state Sprinkle */
	handle->stateConfVector[0] = System_rDefault_Default_Work_Routine_r1_Sprinkle;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state Init */
static void enseq_rDefault_Init_default(System* handle)
{
	/* 'default' enter sequence for state Init */
	enact_rDefault_Init(handle);
	handle->stateConfVector[0] = System_rDefault_Init;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Menu */
static void enseq_rDefault_Menu_default(System* handle)
{
	/* 'default' enter sequence for state Menu */
	enact_rDefault_Menu(handle);
	handle->stateConfVector[0] = System_rDefault_Menu;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Soil Moisture */
static void enseq_rDefault_Soil_Moisture_default(System* handle)
{
	/* 'default' enter sequence for state Soil Moisture */
	handle->stateConfVector[0] = System_rDefault_Soil_Moisture;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state Temperature */
static void enseq_rDefault_Temperature_default(System* handle)
{
	/* 'default' enter sequence for state Temperature */
	handle->stateConfVector[0] = System_rDefault_Temperature;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state Humidity */
static void enseq_rDefault_Humidity_default(System* handle)
{
	/* 'default' enter sequence for state Humidity */
	handle->stateConfVector[0] = System_rDefault_Humidity;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state Air Pressure */
static void enseq_rDefault_Air_Pressure_default(System* handle)
{
	/* 'default' enter sequence for state Air Pressure */
	handle->stateConfVector[0] = System_rDefault_Air_Pressure;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state Rain */
static void enseq_rDefault_Rain_default(System* handle)
{
	/* 'default' enter sequence for state Rain */
	handle->stateConfVector[0] = System_rDefault_Rain;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for state USB */
static void enseq_rDefault_USB_default(System* handle)
{
	/* 'default' enter sequence for state USB */
	handle->stateConfVector[0] = System_rDefault_USB;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* 'default' enter sequence for region rDefault */
static void enseq_rDefault_default(System* handle)
{
	/* 'default' enter sequence for region rDefault */
	react_rDefault__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_rDefault_Default_Work_Routine_r1_default(System* handle)
{
	/* 'default' enter sequence for region r1 */
	react_rDefault_Default_Work_Routine_r1__entry_Default(handle);
}

/* Default exit sequence for state Default Work Routine */
static void exseq_rDefault_Default_Work_Routine(System* handle)
{
	/* Default exit sequence for state Default Work Routine */
	exseq_rDefault_Default_Work_Routine_r1(handle);
}

/* Default exit sequence for state Measure */
static void exseq_rDefault_Default_Work_Routine_r1_Measure(System* handle)
{
	/* Default exit sequence for state Measure */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	exact_rDefault_Default_Work_Routine_r1_Measure(handle);
}

/* Default exit sequence for state Sprinkle */
static void exseq_rDefault_Default_Work_Routine_r1_Sprinkle(System* handle)
{
	/* Default exit sequence for state Sprinkle */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Init */
static void exseq_rDefault_Init(System* handle)
{
	/* Default exit sequence for state Init */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Menu */
static void exseq_rDefault_Menu(System* handle)
{
	/* Default exit sequence for state Menu */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Soil Moisture */
static void exseq_rDefault_Soil_Moisture(System* handle)
{
	/* Default exit sequence for state Soil Moisture */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Temperature */
static void exseq_rDefault_Temperature(System* handle)
{
	/* Default exit sequence for state Temperature */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Humidity */
static void exseq_rDefault_Humidity(System* handle)
{
	/* Default exit sequence for state Humidity */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Air Pressure */
static void exseq_rDefault_Air_Pressure(System* handle)
{
	/* Default exit sequence for state Air Pressure */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state Rain */
static void exseq_rDefault_Rain(System* handle)
{
	/* Default exit sequence for state Rain */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for state USB */
static void exseq_rDefault_USB(System* handle)
{
	/* Default exit sequence for state USB */
	handle->stateConfVector[0] = System_last_state;
	handle->stateConfVectorPosition = 0;
	SC_UNUSED(handle);
}

/* Default exit sequence for region rDefault */
static void exseq_rDefault(System* handle)
{
	/* Default exit sequence for region rDefault */
	/* Handle exit of all possible states (of system.rDefault) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case System_rDefault_Default_Work_Routine_r1_Measure :
		{
			exseq_rDefault_Default_Work_Routine_r1_Measure(handle);
			break;
		}
		case System_rDefault_Default_Work_Routine_r1_Sprinkle :
		{
			exseq_rDefault_Default_Work_Routine_r1_Sprinkle(handle);
			break;
		}
		case System_rDefault_Init :
		{
			exseq_rDefault_Init(handle);
			break;
		}
		case System_rDefault_Menu :
		{
			exseq_rDefault_Menu(handle);
			break;
		}
		case System_rDefault_Soil_Moisture :
		{
			exseq_rDefault_Soil_Moisture(handle);
			break;
		}
		case System_rDefault_Temperature :
		{
			exseq_rDefault_Temperature(handle);
			break;
		}
		case System_rDefault_Humidity :
		{
			exseq_rDefault_Humidity(handle);
			break;
		}
		case System_rDefault_Air_Pressure :
		{
			exseq_rDefault_Air_Pressure(handle);
			break;
		}
		case System_rDefault_Rain :
		{
			exseq_rDefault_Rain(handle);
			break;
		}
		case System_rDefault_USB :
		{
			exseq_rDefault_USB(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_rDefault_Default_Work_Routine_r1(System* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of system.rDefault.Default_Work_Routine.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case System_rDefault_Default_Work_Routine_r1_Measure :
		{
			exseq_rDefault_Default_Work_Routine_r1_Measure(handle);
			break;
		}
		case System_rDefault_Default_Work_Routine_r1_Sprinkle :
		{
			exseq_rDefault_Default_Work_Routine_r1_Sprinkle(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_rDefault__entry_Default(System* handle)
{
	/* Default react sequence for initial entry  */
	enseq_rDefault_Init_default(handle);
}

/* Default react sequence for initial entry  */
static void react_rDefault_Default_Work_Routine_r1__entry_Default(System* handle)
{
	/* Default react sequence for initial entry  */
	enseq_rDefault_Default_Work_Routine_r1_Measure_default(handle);
}

static sc_boolean react(System* handle) {
	SC_UNUSED(handle);
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean rDefault_Default_Work_Routine_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Default Work Routine. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixHash_raised == bool_true)
		{ 
			exseq_rDefault_Default_Work_Routine(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Default_Work_Routine_r1_Measure_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Measure. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.system_rDefault_Default_Work_Routine_r1_Measure_tev0_raised == bool_true)
		{ 
			exseq_rDefault_Default_Work_Routine_r1_Measure(handle);
			enseq_rDefault_Default_Work_Routine_r1_Measure_default(handle);
			rDefault_Default_Work_Routine_react(handle, bool_false);
		}  else
		{
			if (((handle->internal.ConditionsMet_raised) == bool_true) && ((!handle->internal.rain) == bool_true))
			{ 
				exseq_rDefault_Default_Work_Routine_r1_Measure(handle);
				enseq_rDefault_Default_Work_Routine_r1_Sprinkle_default(handle);
				rDefault_Default_Work_Routine_react(handle, bool_false);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = rDefault_Default_Work_Routine_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean rDefault_Default_Work_Routine_r1_Sprinkle_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Sprinkle. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->internal.Raining_raised == bool_true)
		{ 
			exseq_rDefault_Default_Work_Routine_r1_Sprinkle(handle);
			enseq_rDefault_Default_Work_Routine_r1_Measure_default(handle);
			rDefault_Default_Work_Routine_react(handle, bool_false);
		}  else
		{
			if (handle->internal.ConditionsMet_raised == bool_true)
			{ 
				exseq_rDefault_Default_Work_Routine_r1_Sprinkle(handle);
				enseq_rDefault_Default_Work_Routine_r1_Measure_default(handle);
				rDefault_Default_Work_Routine_react(handle, bool_false);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = rDefault_Default_Work_Routine_react(handle, try_transition);
	} 
	return did_transition;
}

static sc_boolean rDefault_Init_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Init. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->internal.InitFinished_raised == bool_true)
		{ 
			exseq_rDefault_Init(handle);
			enseq_rDefault_Default_Work_Routine_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Menu_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Menu. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_Menu(handle);
			enseq_rDefault_Default_Work_Routine_default(handle);
			react(handle);
		}  else
		{
			if (handle->ifaceButtons.matrix1_raised == bool_true)
			{ 
				exseq_rDefault_Menu(handle);
				enseq_rDefault_Soil_Moisture_default(handle);
				react(handle);
			}  else
			{
				if (handle->ifaceButtons.matrix2_raised == bool_true)
				{ 
					exseq_rDefault_Menu(handle);
					enseq_rDefault_Temperature_default(handle);
					react(handle);
				}  else
				{
					if (handle->ifaceButtons.matrix3_raised == bool_true)
					{ 
						exseq_rDefault_Menu(handle);
						enseq_rDefault_Humidity_default(handle);
						react(handle);
					}  else
					{
						if (handle->ifaceButtons.matrix4_raised == bool_true)
						{ 
							exseq_rDefault_Menu(handle);
							enseq_rDefault_Air_Pressure_default(handle);
							react(handle);
						}  else
						{
							if (handle->ifaceButtons.matrix6_raised == bool_true)
							{ 
								exseq_rDefault_Menu(handle);
								enseq_rDefault_USB_default(handle);
								react(handle);
							}  else
							{
								if (handle->ifaceButtons.matrix5_raised == bool_true)
								{ 
									exseq_rDefault_Menu(handle);
									enseq_rDefault_Rain_default(handle);
									react(handle);
								}  else
								{
									did_transition = bool_false;
								}
							}
						}
					}
				}
			}
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Soil_Moisture_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Soil Moisture. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_Soil_Moisture(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Temperature_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Temperature. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_Temperature(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Humidity_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Humidity. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_Humidity(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Air_Pressure_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Air Pressure. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_Air_Pressure(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_Rain_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state Rain. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_Rain(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}

static sc_boolean rDefault_USB_react(System* handle, const sc_boolean try_transition) {
	/* The reactions of state USB. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->ifaceButtons.matrixStar_raised == bool_true)
		{ 
			exseq_rDefault_USB(handle);
			enseq_rDefault_Menu_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} 
	if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} 
	return did_transition;
}


static void system_eventqueue_init(system_eventqueue * eq)
{
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer system_eventqueue_size(system_eventqueue * eq)
{
	return eq->size;
}

static system_internal_event system_eventqueue_pop(system_eventqueue * eq)
{
	system_internal_event event;
	if(system_eventqueue_size(eq) <= 0) {
		system_internal_event_init(&event, system_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < SYSTEM_EVENTQUEUE_BUFFERSIZE - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}

static sc_boolean system_eventqueue_push(system_eventqueue * eq, system_internal_event ev)
{
	if(system_eventqueue_size(eq) == SYSTEM_EVENTQUEUE_BUFFERSIZE) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < SYSTEM_EVENTQUEUE_BUFFERSIZE - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}

static void system_internal_event_init(system_internal_event * ev, system_event_name name)
{
	ev->name = name;
}

static void system_add_event_to_queue(system_eventqueue * eq, system_event_name name)
{
	system_internal_event event;
	system_internal_event_init(&event, name);
	system_eventqueue_push(eq, event);
}

static void system_dispatch_event(System* handle, const system_internal_event * event) {
	switch(event->name) {
		case systemInternal_InitFinished:
		{
			handle->internal.InitFinished_raised = bool_true;
			break;
		}
		case systemInternal_Raining:
		{
			handle->internal.Raining_raised = bool_true;
			break;
		}
		case systemInternal_ConditionsMet:
		{
			handle->internal.ConditionsMet_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static system_internal_event system_get_next_event(System* handle)
{
	system_internal_event next_event;
	system_internal_event_init(&next_event, system_invalid_event);
	if(system_eventqueue_size(&(handle->internal_event_queue)) > 0) {
		next_event = system_eventqueue_pop(&(handle->internal_event_queue));
	}
	return next_event;
}
